@extends('layouts.master')
@section('title','OOO')
@section('content')
<section class="content-header">
    <h1>
        Sliders
        <small>range sliders</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">UI</a></li>
        <li class="active">Sliders</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Ion Slider</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row margin">
                        <div class="col-sm-6">
                            <span class="irs js-irs-0"><span class="irs"><span class="irs-line" tabindex="-1"><span class="irs-line-left"></span><span class="irs-line-mid"></span><span class="irs-line-right"></span></span><span style="visibility: visible;" class="irs-min">$0</span><span style="visibility: visible;" class="irs-max">$5 000</span><span style="visibility: visible; left: 14.4617%;" class="irs-from">$799</span><span style="visibility: visible; left: 74.9293%;" class="irs-to">$4 000</span><span style="visibility: hidden; left: 41.4632%;" class="irs-single">$799 — $4 000</span></span><span class="irs-grid"></span><span style="left: 17.492%; width: 61.1747%;" class="irs-bar"></span><span style="display: none;" class="irs-shadow shadow-from"></span><span style="display: none;" class="irs-shadow shadow-to"></span><span style="left: 15.2698%;" class="irs-slider from type_last"></span><span style="left: 76.4445%;" class="irs-slider to"></span></span><input readonly="" class="irs-hidden-input" id="range_1" name="range_1" value="" type="text">
                        </div>

                        <div class="col-sm-6">
                            <input id="range_2" name="range_2" value="1000;100000" data-type="double" data-step="500" data-postfix=" €" data-from="30000" data-to="90000" data-hasgrid="true" type="text">
                        </div>
                    </div>
                    <div class="row margin">
                        <div class="col-sm-6">
                            <input id="range_5" name="range_5" value="" type="text">
                        </div>
                        <div class="col-sm-6">
                            <input id="range_6" name="range_6" value="" type="text">
                        </div>
                    </div>
                    <div class="row margin">
                        <div class="col-sm-12">
                            <input id="range_4" name="range_4" value="10000;100000" type="text">
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Bootstrap Slider</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row margin">
                        <div class="col-sm-6">
                            <div id="red" class="slider slider-horizontal"><div class="slider-track"><div style="left: 0px; width: 25%;" class="slider-track-low"></div><div style="left: 25%; width: 50%;" class="slider-selection"></div><div style="right: 0px; width: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="left: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="left: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 50%; margin-left: -35.5px;" role="presentation" class="tooltip tooltip-main top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 25%; margin-left: -20.5px; display: none;" role="presentation" class="tooltip tooltip-min top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 75%; margin-left: -18.5px; display: none;" role="presentation" class="tooltip tooltip-max top"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="horizontal" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="red" type="text">

                            <p>data-slider-id="red"</p>
                            <div id="blue" class="slider slider-horizontal"><div class="slider-track"><div style="left: 0px; width: 25%;" class="slider-track-low"></div><div style="left: 25%; width: 50%;" class="slider-selection"></div><div style="right: 0px; width: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="left: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="left: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 50%; margin-left: -35.5px;" role="presentation" class="tooltip tooltip-main top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 25%; margin-left: -20.5px; display: none;" role="presentation" class="tooltip tooltip-min top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 75%; margin-left: -18.5px; display: none;" role="presentation" class="tooltip tooltip-max top"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="horizontal" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="blue" type="text">

                            <p>data-slider-id="blue"</p>
                            <div id="green" class="slider slider-horizontal"><div class="slider-track"><div style="left: 0px; width: 25%;" class="slider-track-low"></div><div style="left: 25%; width: 50%;" class="slider-selection"></div><div style="right: 0px; width: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="left: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="left: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 50%; margin-left: -35.5px;" role="presentation" class="tooltip tooltip-main top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 25%; margin-left: -20.5px;" role="presentation" class="tooltip tooltip-min top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 75%; margin-left: -18.5px;" role="presentation" class="tooltip tooltip-max top"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="horizontal" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="green" type="text">

                            <p>data-slider-id="green"</p>
                            <div id="yellow" class="slider slider-horizontal"><div class="slider-track"><div style="left: 0px; width: 25%;" class="slider-track-low"></div><div style="left: 25%; width: 50%;" class="slider-selection"></div><div style="right: 0px; width: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="left: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="left: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 50%; margin-left: -35.5px;" role="presentation" class="tooltip tooltip-main top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 25%; margin-left: -20.5px;" role="presentation" class="tooltip tooltip-min top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 75%; margin-left: -18.5px;" role="presentation" class="tooltip tooltip-max top"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="horizontal" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="yellow" type="text">

                            <p>data-slider-id="yellow"</p>
                            <div id="aqua" class="slider slider-horizontal"><div class="slider-track"><div style="left: 0px; width: 25%;" class="slider-track-low"></div><div style="left: 25%; width: 50%;" class="slider-selection"></div><div style="right: 0px; width: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="left: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="left: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 50%; margin-left: -35.5px;" role="presentation" class="tooltip tooltip-main top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 25%; margin-left: -20.5px;" role="presentation" class="tooltip tooltip-min top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 75%; margin-left: -18.5px;" role="presentation" class="tooltip tooltip-max top"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="horizontal" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="aqua" type="text">

                            <p>data-slider-id="aqua"</p>
                            <div id="purple" class="slider slider-horizontal"><div class="slider-track"><div style="left: 0px; width: 25%;" class="slider-track-low"></div><div style="left: 25%; width: 50%;" class="slider-selection"></div><div style="right: 0px; width: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="left: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="left: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 50%; margin-left: -35.5px;" role="presentation" class="tooltip tooltip-main top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 25%; margin-left: -20.5px;" role="presentation" class="tooltip tooltip-min top"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 75%; margin-left: -18.5px;" role="presentation" class="tooltip tooltip-max top"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="horizontal" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="purple" type="text">

                            <p style="margin-top: 10px">data-slider-id="purple"</p>
                        </div>
                        <div class="col-sm-6 text-center">
                            <div id="red" class="slider slider-vertical"><div class="slider-track"><div style="top: 0px; height: 25%;" class="slider-track-low"></div><div style="top: 25%; height: 50%;" class="slider-selection"></div><div style="bottom: 0px; height: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="top: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="top: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 100%; top: 50%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-main right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 100%; top: 25%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-min right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 100%; top: 75%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-max right"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="vertical" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="red" type="text">
                            <div id="blue" class="slider slider-vertical"><div class="slider-track"><div style="top: 0px; height: 25%;" class="slider-track-low"></div><div style="top: 25%; height: 50%;" class="slider-selection"></div><div style="bottom: 0px; height: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="top: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="top: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 100%; top: 50%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-main right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 100%; top: 25%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-min right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 100%; top: 75%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-max right"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="vertical" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="blue" type="text">
                            <div id="green" class="slider slider-vertical"><div class="slider-track"><div style="top: 0px; height: 25%;" class="slider-track-low"></div><div style="top: 25%; height: 50%;" class="slider-selection"></div><div style="bottom: 0px; height: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="top: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="top: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 100%; top: 50%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-main right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 100%; top: 25%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-min right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 100%; top: 75%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-max right"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="vertical" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="green" type="text">
                            <div id="yellow" class="slider slider-vertical"><div class="slider-track"><div style="top: 0px; height: 25%;" class="slider-track-low"></div><div style="top: 25%; height: 50%;" class="slider-selection"></div><div style="bottom: 0px; height: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="top: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="top: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 100%; top: 50%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-main right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 100%; top: 25%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-min right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 100%; top: 75%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-max right"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="vertical" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="yellow" type="text">
                            <div id="aqua" class="slider slider-vertical"><div class="slider-track"><div style="top: 0px; height: 25%;" class="slider-track-low"></div><div style="top: 25%; height: 50%;" class="slider-selection"></div><div style="bottom: 0px; height: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="top: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="top: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 100%; top: 50%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-main right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 100%; top: 25%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-min right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 100%; top: 75%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-max right"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="vertical" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="aqua" type="text">
                            <div id="purple" class="slider slider-vertical"><div class="slider-track"><div style="top: 0px; height: 25%;" class="slider-track-low"></div><div style="top: 25%; height: 50%;" class="slider-selection"></div><div style="bottom: 0px; height: 25%;" class="slider-track-high"></div><div tabindex="0" aria-valuenow="-100" style="top: 25%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle min-slider-handle round"></div><div tabindex="0" aria-valuenow="100" style="top: 75%;" aria-valuemax="200" aria-valuemin="-200" role="slider" class="slider-handle max-slider-handle round"></div></div><div style="left: 100%; top: 50%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-main right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100 : 100</div></div><div style="left: 100%; top: 25%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-min right"><div class="tooltip-arrow"></div><div class="tooltip-inner">-100</div></div><div style="left: 100%; top: 75%; margin-top: -11.5px;" role="presentation" class="tooltip tooltip-max right"><div class="tooltip-arrow"></div><div class="tooltip-inner">100</div></div></div><input data-value="-100,100" style="display: none;" value="-100,100" class="slider form-control" data-slider-min="-200" data-slider-max="200" data-slider-step="5" data-slider-value="[-100,100]" data-slider-orientation="vertical" data-slider-selection="before" data-slider-tooltip="show" data-slider-id="purple" type="text">
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@endsection
@section('scripts')
@endsection